### ISSUE TITLE
”issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by erika328** [erika328/SpeakUp#26]
### 実装予定の機能
- [ ] 単語登録機能
- [ ] 発音採点機能（API）
- [ ] 単語翻訳機能（API）
- [ ] 単語翻訳機能のオートコンプリート
- [ ] マイページの単語検索機能
- [ ] 英文読み上げ機能（API）
- [ ] Google認証ログイン機能
- [ ] パスワードリセット機能
- [ ] 採点結果のランキング化機能
- [ ] お試しログイン機能

### 必要なページ
- [ ] トップページ
- [ ] マイページ
- [ ] ログインページ
- [ ] 新規会員登録ページ
- [ ] パスワード再設定メール送信ページ
- [ ] パスワード再設定ページ
- [ ] 利用規約ページ
- [ ] プライバシーポリシーページ
- [ ] お問い合わせページ
- [ ] シャドーイングレッスン動画一覧ページ
- [ ] シャドーイングレッスンページ
- [ ] 発音採点ページ
- [ ] お試しログイン用シャドーイングレッスンページ
- [ ] お試しログイン用発音採点ページ

ProjectのURL
https://github.com/users/erika328/projects/3

お試しログインのページは別で用意するのか、既存のものにアクセス制限を設けてするのか迷っています。アドバイスいただけると幸いです。

**Comment by shota-hope** [comment]
ご提出ありがとうございます。
Projectについて、問題ないと思います。

疑問点について
> お試しログインのページは別で用意するのか、既存のものにアクセス制限を設けてするのか

もう少し具体的にご説明いただけますでしょうか🙏
ご確認よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
細かくissueを切っておいた方が進捗を感じながら進められる&実装がより可視化されるので、以降もできる限り細かいissueを立てるようにしましょう。

**Comment by shota-hope** [comment]
疑問点について
説明ありがとうございます。
後者の方がいいと思いました！

> 試してほしい機能が二つのみなので、その機能をいっそのことトップページに貼り付けるのもいいのかな…とも思っています。

個人的に良いと思うのは、ログインしていなくても試してほしい機能が使えて、保存したいなら登録する必要があるという状態かなと思いました。
それであればゲストログイン自体が必要ないかもしれません。
あくまでイチ意見としてですが、ご確認よろしくお願いします。
